server:
  port: 8082
spring:
  application:
    name: papertranslate
  http:
    multipart:
      max-file-size: 1000MB
  servlet:
    multipart:
      max-request-size: 2000MB
      max-file-size: 2000MB
  redis:
    database: 0
    host: www.lighttools.ltd
    port: 6379
    password:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: lwg.cool:8848